import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { SignIn } from "@clerk/nextjs";
import { Button } from "components/ui/button";
import Link from "next/link";

const Profile = () => {
  const { user } = useUser();
  console.log({ user });
  return <p>{user?.username}</p>;
};

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();
  console.log(user);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>
          <Profile />
          <Link href="account">account</Link>
          {!user.isSignedIn && (
            <Button className="bg-rose-500 text-secondary duration-300 ease-in-out hover:bg-rose-600 active:scale-90">
              <SignInButton />
            </Button>
          )}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        <div>
          {data?.map((post) => (
            <div key={post.id}>{post.content}</div>
          ))}
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default Home;
